---
title: "Incorporated Software & Media"
order: 3
---

## Licensing Statements for Incorporated Software

The R software is licensed under the General Public License version 2 or Later. The language of the licensing can be accessed using the command below:

```         
RShowDoc("GPL-3")
```

The tidyverse packages, including dplyr, ggplot2, tidyr, and others are licensed under the MIT license, which can be [accessed here](https://tidyverse.tidyverse.org/LICENSE.html).

Quarto, the framework used to build this guide, is licensed under the General Public License version 2, which can be [accessed here](https://quarto.org/license.html).

The RStudio IDE software is provided under the Affero General Public License version 3, which can be [accessed here](https://www.gnu.org/licenses/agpl-3.0-standalone.html).

The webR package is licensed under the MIT license with the binaries licensed under the General Public License version 3. Information can be [accessed here](https://github.com/r-wasm/webr/blob/main/LICENSE.md).

The icon is an adaption, (c) Joseph Gage, some rights reserved (CC BY-SA)
